module.exports = {
	popUpWindow: "div[role='alertdialog']",
	dismissBtn: "//input[@data-action-type='DISMISS' and @type='submit']",
	giftCardTab: "(//a[contains(text(),'Gift Cards')])[1]",
	animatedChecBox: "(//i[@class='a-icon a-icon-checkbox'])[6]",
	cardDesigns: "#gc-design-mini-picker",
	priceLow: "#low-price",
	priceHigh: "#high-price",
	goButton: "input.a-button-input",
	firstItem: "(//img[@alt='Amazon.com eGift Card'])[1]",
	eGiftCardTitle: "#gc-asin-title",
	gitCardUrl:
		"https://www.amazon.com/Amazon-eGift-Card-Birthday-Animated/dp/B09LQTPHSG/",
	amountTextBox: "#gc-order-form-custom-amount",
	validateAmount: "#gc-live-preview-amount",
	toField: "#gc-order-form-recipients",
	nameField: "#gc-order-form-senderName",
	messageField: "#gc-order-form-message",
	quantityField: "#gc-order-form-quantity",
	deliveryDateField: "#gc-order-form-date-val",
	selectDate: "(//a[normalize-space()='31'])[1]",
	addToCartButton: "#gc-buy-box-atc",
	icon: ".a-box.a-alert-inline.a-alert-inline-success.sw-atc-message",
	endPointOne:
		"/cart/ewc/compact?hostPageType=ShoppingCartAdd&hostSubPageType=SmartWagonFullPage&hostPageRID=SPWGYZWYXHJVZ0NQ0PMS&prerender=0&freshCartCount=0&almCartCount=0&widerCompactView=true&_=1638568131057",
};
